#ifndef _FLOCONS_HTTP_H_
#define _FLOCONS_HTTP_H_

enum HTTPCode { CONTINUE = 100, OK = 200, TEMPORARY_REDIRECT = 307, BAD_REQUEST = 400, NOT_FOUND = 404, INTERNAL_SERVER_ERROR = 500, BAD_GATEWAY = 502 };

#define HTTP_HEADER_CONTENT_LENGTH "Content-Length"
#define HTTP_HEADER_CONTENT_TYPE "Content-Type"
#define HTTP_HEADER_LAST_MODIFIED "Last-Modified"
#define HTTP_HEADER_LOCATION "Location"
#define HTTP_HEADER_FILE_MODE "X-Content-File-Mode"

#endif // !_FLOCONS_HTTP_H_